// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhoyqesysyxpfxmpscnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impob3lxZXN5c3l4cGZ4bXBzY25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjg5NDgsImV4cCI6MjA2NTc0NDk0OH0.fsgonKwzMZXknrLdaypKxdVX5m372mTF9EnN29xmsuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);